# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-22 03:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creat_time', models.TimeField(auto_created=True, verbose_name='blog时间')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('contents', models.TextField(max_length=1500, verbose_name='内容')),
                ('like', models.IntegerField(blank=True, null=True, verbose_name='喜欢数')),
                ('counts', models.IntegerField(blank=True, null=True, verbose_name='点击次数')),
                ('comments', models.IntegerField(blank=True, null=True, verbose_name='评论数')),
                ('user', models.CharField(blank=True, max_length=20, null=True, verbose_name='作者')),
                ('tag', models.CharField(blank=True, max_length=20, verbose_name='标签')),
            ],
            options={
                'ordering': ['-creat_time'],
                'verbose_name_plural': '文章',
                'verbose_name': '文章',
            },
        ),
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creat_time', models.TimeField(auto_created=True, verbose_name='评论时间')),
                ('contents', models.TextField(max_length=150, verbose_name='评论内容')),
                ('user', models.CharField(max_length=20, verbose_name='用户')),
                ('blogtitle', models.CharField(max_length=20, verbose_name='标题')),
            ],
            options={
                'ordering': ['-creat_time'],
                'verbose_name_plural': '评论',
                'verbose_name': '评论',
            },
        ),
        migrations.CreateModel(
            name='tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='标签')),
            ],
            options={
                'verbose_name_plural': '标签',
                'verbose_name': '标签',
            },
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10, verbose_name='用户名')),
                ('password', models.CharField(max_length=20, verbose_name='密码')),
            ],
            options={
                'ordering': ['-id'],
                'verbose_name_plural': '用户',
                'verbose_name': '用户',
            },
        ),
    ]
