# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-22 06:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='blog_user',
        ),
    ]
